# Generated by Django 2.1.5 on 2019-02-04 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('likes', models.IntegerField()),
                ('thumbnail_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('count_sold', models.IntegerField()),
                ('phot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_no', models.IntegerField()),
                ('photographer_photo', models.ImageField(blank=True, upload_to='')),
                ('paypal_id', models.TextField()),
                ('category', models.TextField()),
                ('experience', models.FloatField()),
                ('description', models.TextField()),
                ('availibility', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photographer'),
        ),
    ]
